### ISSUE TITLE
Bug translate

### ISSUE THREAD

**Issue by evgarik** [codeout/inet-henge#7] opened 2018-05-23 12:41 UTC
I use
`diagram.svg.attr('transform', 'translate(100, 100) scale(1.5)');`
It turns out to move the map. but when you try to move the map, you jump to the coordinates before moving

**Comment by codeout** [comment] 2018-05-24 01:01
Could you try the latest version? The problem was fixed at #3.

**Comment by evgarik** [comment] 2018-05-24 05:11
I'm using the latest version
attached to button
`diagram.svg.attr('transform', 'translate(100, 100) scale(1.5)');`

I check:
1. I move the map with the mouse
2. Click on the button
3. I try to move the map again with the mouse

the same with zoom

**Comment by codeout** [comment] 2018-05-24 05:37
Thanks for the comment. Let me try to reproduce it.

**Comment by codeout** [comment] 2018-07-24 17:19
I've just pushed the fix. Could you try the latest code please?

**Comment by codeout** [comment] 2018-07-24 17:35
Try

```js
diagram.attr('transform', 'translate(100, 100) scale(1.5)');
```

instead of

```
diagram.svg.attr('transform', 'translate(100, 100) scale(1.5)');
```

**Closed** 2019-07-06 13:39 UTC
